#!/bin/sh

if [ "$PKG_UPGRADE" != 1 ]; then
	uci get luci.themes.noir >/dev/null 2>&1 ||
		uci batch <<-EOF
			set luci.themes.noir=/luci-static/noir
			set luci.main.mediaurlbase=/luci-static/noir
			commit luci
		EOF
fi

exit 0
